package com.belhard.univercity;

public enum Country {
	BELARUS, POLAND, UKRAINE, RUSSIA, LATVIA, LITHUANIA, ESTONIA, CHECK_REPUBLIC, MOLDOVA, GERMANY, FRANCE, GREATE_BRITAIN, ITALY, GREACE, TURKEY
}
